### ISSUE TITLE
Questions about taxcalc memory usage in AWS Docker container

### ISSUE THREAD

**Issue by martinholmer** [ospc-org/ospc.org#880]
@hdoupe said in closed issue #861:
> Resolved via open-source-economics/Tax-Calculator#1942. The test app is currently running on r4-large instances with no problems. We are still getting a memory usage spike around 12.5 GB. That gives us about a 2 GB margin of error. This is something we should keep in mind.
>
> One way to test this in the future is running Tax-Calculator in Docker containers. You can toggle the available memory for a container up to your machine's memory limits. For example, you could simulate only having 5 GB of RAM, and your process will be killed if it goes over just like if you only had 5 GB of RAM on your machine.
>
> However, my knowledge of this area is pretty limited. So, if anyone else has ideas on how to do this, then I am interested in discussing them.
>
> Thanks for quickly fixing this @martinholmer.

Thanks for the PolicyBrain test report on memory usage by the release 0.18.0 taxcalc package.
The information you provide is interesting but I know nothing about Docker containers, and therefore, have questions.  Let me start with a basic question:

When you say memory usage peaked at 12.5GB, what is included in the 12.5GB?

Or putting it a different way.

What is memory usage just before making the call to the `run_nth_year_tax_calc_model` function?

**Comment by hdoupe** [comment]
@martinholmer asked:
> What is memory usage just before making the call to the run_nth_year_tax_calc_model function?

Here is a screen shot of the CPU/memory usage in an idle state:

<img width="509" alt="screen shot 2018-03-30 at 7 11 05 pm" src="https://user-images.githubusercontent.com/9206065/38156753-736fa2d6-344e-11e8-9a37-fcdbea302a6f.png">

It looks like we are hovering around 2 GB of memory usage. When you submit a job and are applying the numba functions it looks something like:

<img width="490" alt="screen shot 2018-03-30 at 7 16 01 pm" src="https://user-images.githubusercontent.com/9206065/38156800-ee6615d8-344e-11e8-8f53-d367cc588c3f.png">

Then, when the tables are being created, the memory usage begins to climb:

<img width="514" alt="screen shot 2018-03-30 at 7 16 33 pm" src="https://user-images.githubusercontent.com/9206065/38156811-03e096b8-344f-11e8-98c9-613fe6fc98ef.png">

However, you can replicate most of this locally which is what makes Docker really useful and interesting. I'll put some documentation together so that anyone who is interested and has permission (due to the PUF file) can run the worker node docker containers.

I'm still a little fuzzy on how everything fits together. But the high level view is: 
1. Flask is the web server that fields requests and submits them to Celery.
2. Celery is what runs the model. It is useful because when you run a function in celery you are starting an asynchronous process and can go back to handling requests and submitting more jobs.
3. Redis is the database that Celery uses to keep track of the job queue.

So, Celery is the service that you want to look at for tracking Tax-Calculator memory usage.

**Comment by martinholmer** [comment]
@hdoupe,  Thanks for the explanation of memory usage in the Docker container on AWS.
In the screen shots you show that memory usage rises from idle 1.9GB to 9.9GB, which is an increase of 8GB.
Earlier you mentioned a situation in which memory usage was as hight as 12.5GB.  What was happening when it got that high?

**Comment by hdoupe** [comment]
@martinholmer  asked: 
> Earlier you mentioned a situation in which memory usage was as hight as 12.5GB. What was happening when it got that high?

That's just a little further along in the table building process.

**Comment by hdoupe** [comment]
@martinholmer In PR #884 I added some documentation to help people get started with Docker. If you have time and are interested, I would appreciate any thoughts you may have on how to make that documentation more clear.

**Comment by martinholmer** [comment]
Issue #880 was resolved many months ago by an extensive refactoring of the `taxcalc/tbi` results construction logic.  Those changes in `taxcalc/tbi` reduced significantly the result-creation memory usage.  My memory of it was that the memory reduction was so substantial that a smaller AWS instance was able to be used to run Tax-Calculator, and that the smaller AWS instance had an hourly rental fee that was half of the AWS instance that was formerly required by the inefficient results-creation logic.

**Comment by hdoupe** [comment]
@martinholmer thanks for all of your work to reduce Tax-Calculator's memory usage. If you have any more questions about how to use docker to simulate Tax-Calculator's memory usage on the weabapp servers, please reach out to me and I am happy to discuss.
